backend:
  name: github
  repo: PerfectPan/blog

media_folder: static/assets
public_folder: assets

collections:
  - name: Web
    label: FE
    folder: content/fe
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tag, label: Tag, widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: 生活琐事
    label: Life
    folder: content/life
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tag, label: Tag, widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: 数据结构和算法
    label: Algorithm
    folder: content/algorithm
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tag, label: Tag, widget: list }
      - { name: body, label: Body, widget: markdown }
    
