backend:
  name: github
  repo: PerfectPan/blog

media_folder: static/assets
public_folder: assets

collections:
  - name: Web
    label: blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tag, label: Tag, widget: list }
      - { name: body, label: Body, widget: markdown }
    
