// Minimal typing for the worker `env` accessor used to reach bindings
// (the D1 database) at module scope. The full binding surface is generated by
// `pnpm exec wrangler types`; this keeps `tsc` self-contained.
declare module 'cloudflare:workers' {
  export const env: Record<string, unknown> & {
    DB: D1Database;
  };
}
