// Minimal typing for the worker `env` accessor used to reach bindings
// (the D1 database) at module scope. The full binding surface is generated by
// `pnpm exec wrangler types`; this keeps `tsc` self-contained.
declare module 'cloudflare:workers' {
  export const env: Record<string, unknown> & {
    DB: D1Database;
  };
}

// Build-scoped constant injected by vite `define` (see vite.config.ts): every
// build produces a new value, which page-cache.ts folds into the Cache API
// namespace so a redeploy can never serve edge HTML that references asset
// hashes from a previous deployment.
declare const __ARTICLE_CACHE_BUILD_ID__: string;
